version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/events
      JWT_SECRET_KEY: change-me-in-env
      JWT_ALGORITHM: HS256
      CORS_ALLOWED_ORIGINS: http://localhost:5173
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: bash -lc "npm run dev -- --host 0.0.0.0"

volumes:
  pgdata:

